volumes:
  postgres-data:
  redis-data:
  pgadmin-data:

networks:
  backend:

services:
  app:
    container_name: javadev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in db container
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: postgresdb
      REDIS_HOST: redis
      REDIS_HOSTNAME: redis

    volumes:
      - ..:/workspaces/user-service:cached
    depends_on:
      - db
      - redis
      - pgadmin

    ports:
      - 8080:8080
      - 8081:8081
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    networks:
      - backend

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally. 
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    container_name: postgresdb
    image: postgres:15.4
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      # NOTE: POSTGRES_DB/USER/PASSWORD should match values in app container
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - backend

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis:
    container_name: redis
    image: redis:7.0.11
    restart: unless-stopped
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    networks:
      - backend

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    ports:
      - 5050:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - backend
    # Add "forwardPorts": ["80"] to **devcontainer.json** to forward pgAdmin locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)
    # Access pgAdmin at http://localhost:80 with admin@admin.com / admin
